language: minimal

before_install:
  - echo hello travis
  - echo $TRAVIS_BRANCH
  - pip install --user awscli

install:
  - aws --version
  - export AWS_ACCESS_KEY_ID=$aws29_dev_access_key_id;
  - export AWS_SECRET_ACCESS_KEY=$aws29_dev_secret_access_key;
  - aws s3 ls --region ap-northeast-1 --output json